# Generated by Django 5.2.8 on 2025-11-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expirable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product_batch',
            name='batch_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_batch',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
