# Generated by Django 5.2.8 on 2025-11-16 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0002_purchase_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenant_data.sale')),
            ],
            options={
                'verbose_name': 'Sales Item',
                'verbose_name_plural': 'Sales Items',
                'ordering': ['-sale__created_at'],
            },
        ),
    ]
