# Generated by Django 5.2.8 on 2025-11-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0002_product_expirable_alter_product_batch_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='batch_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
