# Generated by Django 5.2.8 on 2025-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_data', '0003_alter_purchaseitem_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='batch_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
